name: goreleaser

on:
  pull_request:
  push:

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v3
      -
        name: Build
        run: |
          make all
      -
        name: Upload binaries to release
        if: github.event_name != 'pull_request'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.BUILDER_GITHUB_ACTIONS_TOKEN }}
          file: ./build/bin/geth.exe
          asset_name: berylbit-miner-geth-windows.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "BerylBit experimental Geth"
