name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: ${{ github.event.repository.name }}
  PACKAGE_VERSION: 0.0.${{ github.ref != 'refs/heads/main' && format('{0}-{1}.{2}', github.run_number, github.ref_name, github.run_attempt) || github.run_number }}

jobs:
  push-image-to-docker-hub:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Login to Docker Hub
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:$PACKAGE_VERSION
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:$PACKAGE_VERSION
