name: goreleaser

on:
  pull_request:
  push:

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v3
      -
        name: Build
        run: |
          make all
      - 
        name: Release
        run: |
          cd ./build/bin
          ls
