name: make-alloc

on:
  push:

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v3
      -
        name: make-alloc
        run: |
          go run core\mkalloc.go berylbit_genesis.json